---
layout: mypost
title: 前端异常处理
categories: [javascript]
---

# Try-Catch

## 同步运行时错误(可以捕获)
```
try {
  let name = 'jartto';
  console.log(nam);	//这里故意写错
} catch(e) {
  console.log('捕获到异常：',e);
}
//捕获到异常： ReferenceError: nam is not defined
//    at <anonymous>:3:15
```

## 语法错误，我们删掉一个单引号(无法捕获)
```
try {
  let name = 'jartto;	//这里少写一个单引号
  console.log(nam);
} catch(e) {

  console.log('捕获到异常：',e);
}
//Uncaught SyntaxError: Invalid or unexpected token
```
不过语法错误在我们开发阶段就可以看到，应该不会顺利上到线上环境。

## 异步错误(无法捕获)
```
try {
  setTimeout(() => {
    undefined.map(v => v);
  }, 1000)
} catch(e) {
  console.log('捕获到异常：',e);
}

//Uncaught TypeError: Cannot read property 'map' of undefined
//    at setTimeout (<anonymous>:3:11)
```
并没有捕获到异常，这是需要我们特别注意的地方。


# window.onerror

当 JS 运行时错误发生时，window 会触发一个 ErrorEvent 接口的 error 事件，并执行 window.onerror()。

## 同步运行时错误(可捕获)
```
window.onerror = function(message, source, lineno, colno, error) {
	// message：错误信息（字符串）。
	// source：发生错误的脚本URL（字符串）
	// lineno：发生错误的行号（数字）
	// colno：发生错误的列号（数字）
	// error：Error对象（对象）
	console.log('捕获到异常：',{message, source, lineno, colno, error});
}
Jartto;
// 捕获到异常：
// ...
```
上面代码写在html中可捕获到异常，直接在控制台使用无法捕获

## 语法错误（无法捕获）
```
window.onerror = function(message, source, lineno, colno, error) {
	console.log('捕获到异常：',{message, source, lineno, colno, error});
}
let name = 'Jartto	//少一个单引号

//Uncaught SyntaxError: Invalid or unexpected token
```

## 异步运行（可以捕获）
```
window.onerror = function(message, source, lineno, colno, error) {
    console.log('捕获到异常：',{message, source, lineno, colno, error});
}
setTimeout(() => {
    Jartto;
});


//捕获到异常： {message: "Script error.", source: "", lineno: 0, colno: 0, error: null}
```

## 网络请求异常(无法捕获)
```
<script>
window.onerror = function(message, source, lineno, colno, error) {
    console.log('捕获到异常：',{message, source, lineno, colno, error});
    return true;
}
</script>
<img src="./jartto.png">
```
我们发现，不论是静态资源异常，或者接口异常，错误都无法捕获到。

补充一点：window.onerror 函数只有在返回 true 的时候，异常才不会向上抛出，否则即使是知道异常的发生控制台还是会显示 Uncaught Error: xxxxx

```
window.onerror = function(message, source, lineno, colno, error) {
    console.log('捕获到异常：',{message, source, lineno, colno, error});
    return true;
}
setTimeout(() => {
    Jartto;
});

//控制台就不会再有这样的错误了：
//Uncaught ReferenceError: Jartto is not defined
//    at setTimeout ((index):36)
```

需要注意：

- onerror 最好写在所有 JS 脚本的前面，否则有可能捕获不到错误；
- onerror 无法捕获语法错误；

到这里基本就清晰了：在实际的使用过程中，onerror 主要是来捕获预料之外的错误，而 try-catch 则是用来在可预见情况下监控特定的错误，两者结合使用更加高效。

问题又来了，捕获不到静态资源加载异常怎么办？


# window.addEventListener

当一项资源（如图片或脚本）加载失败，加载资源的元素会触发一个 Event 接口的 error 事件，并执行该元素上的onerror() 处理函数。这些 error 事件不会向上冒泡到 window ，不过（至少在 Firefox 中）能被单一的window.addEventListener 捕获。
```
<script>
window.addEventListener('error', (error) => {
	console.log('捕获到异常：', error);
}, true)
</script>
<img src="./jartto.png">

// 捕获到异常： Event {isTrusted: true, type: "error", target: img, currentTarget: Window, eventPhase: 1, …}
```

由于网络请求异常不会事件冒泡，因此必须在捕获阶段将其捕捉到才行，但是这种方式虽然可以捕捉到网络请求的异常，但是无法判断 HTTP 的状态是 404 还是其他比如 500 等等，所以还需要配合服务端日志才进行排查分析才可以。

需要注意：

- 不同浏览器下返回的 error 对象可能不同，需要注意兼容处理。
- 需要注意避免 addEventListener 重复监听。


# Promise Catch

在 promise 中使用 catch 可以非常方便的捕获到异步 error 。

没有写 catch 的 Promise 中抛出的错误无法被 onerror 或 try-catch 捕获到，所以我们务必要在 Promise 中不要忘记写 catch 处理抛出的异常。

解决方案： 为了防止有漏掉的 Promise 异常，建议在全局增加一个对 unhandledrejection 的监听，用来全局监听Uncaught Promise Error。使用方式：
```
window.addEventListener("unhandledrejection", function(e){
	e.preventDefault();	//去掉控制台的异常显示
	console.log('捕获到异常：', e);
	return true;
});
Promise.reject('promise error');

//捕获到异常： PromiseRejectionEvent {isTrusted: true, promise: Promise, reason: "promise error", type: "unhandledrejection", target: Window, …}
```

那如果对 Promise 不进行 catch 呢？
```
window.addEventListener("unhandledrejection", function(e){
	e.preventDefault()
	console.log('捕获到异常：', e);
	return true;
});
new Promise((resolve, reject) => {
	reject('jartto: promise error');
});
```
也是会被正常捕获到的。

所以，为了防止有漏掉的 Promise 异常，建议在全局增加一个对 unhandledrejection 的监听，用来全局监听 Uncaught Promise Error。


# VUE errorHandler
```
Vue.config.errorHandler = (err, vm, info) => {
	console.error('通过vue errorHandler捕获的错误');
	console.error(err);
	console.error(vm);
	console.error(info);
}
```


# React 异常捕获

React 16 提供了一个内置函数 componentDidCatch，使用它可以非常简单的获取到 react 下的错误信息
```
componentDidCatch(error, info) {
    console.log(error, info);
}
```
除此之外，我们可以了解一下：error boundary

UI 的某部分引起的 JS 错误不应该破坏整个程序，为了帮 React 的使用者解决这个问题，React 16 介绍了一种关于错误边界（error boundary)的新观念。

需要注意的是： error boundaries 并不会捕捉下面这些错误。

- 事件处理器
- 异步代码
- 服务端的渲染代码
- 在 error boundaries 区域内的错误

我们来举一个小例子，在下面这个 componentDIdCatch(error,info) 里的类会变成一个 error boundary：
```
class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false };
  }
 
  componentDidCatch(error, info) {
    // Display fallback UI
    this.setState({ hasError: true });
    // You can also log the error to an error reporting service
    logErrorToMyService(error, info);
  }
 
  render() {
    if (this.state.hasError) {
      // You can render any custom fallback UI
      return <h1>Something went wrong.</h1>;
    }
    return this.props.children;
  }
}
```
然后我们像使用普通组件那样使用它：
```
<ErrorBoundary>
	<MyWidget />
</ErrorBoundary>
```
componentDidCatch() 方法像 JS 的 catch{} 模块一样工作，但是对于组件，只有 class 类型的组件(class component )可以成为一个 error boundaries。

实际上，大多数情况下我们可以在整个程序中定义一个 error boundary 组件，之后就可以一直使用它了！


# iframe 异常

对于 iframe 的异常捕获，我们还得借力 window.onerror：
```
<iframe src="./iframe.html" frameborder="0"></iframe>
<script>
  window.frames[0].onerror = function (message, source, lineno, colno, error) {
    console.log('捕获到 iframe 异常：',{message, source, lineno, colno, error});
    return true;
  };
</script>
```
*但亲自试验后，iframe.html中抛出的异常无法在当前页面捕获到*


# 崩溃和卡顿

卡顿也就是网页暂时响应比较慢， JS 可能无法及时执行。但崩溃就不一样了，网页都崩溃了，JS 都不运行了，还有什么办法可以监控网页的崩溃，并将网页崩溃上报呢？

## 利用 window 对象的 load 和 beforeunload 事件实现了网页崩溃的监控。

```
  window.addEventListener('load', function () {
    sessionStorage.setItem('good_exit', 'pending');
    setInterval(function () {
        sessionStorage.setItem('time_before_crash', new Date().toString());
    }, 1000);
  });

  window.addEventListener('beforeunload', function () {
    sessionStorage.setItem('good_exit', 'true');
  });

  if(sessionStorage.getItem('good_exit') &&
    sessionStorage.getItem('good_exit') !== 'true') {
    /*
        insert crash logging code here
    */
    alert('Hey, welcome back from your crash, looks like you crashed on: ' + sessionStorage.getItem('time_before_crash'));
  }
```

## 基于以下原因，我们可以使用 Service Worker 来实现网页崩溃的监控：

Service Worker 有自己独立的工作线程，与网页区分开，网页崩溃了，Service Worker一般情况下不会崩溃；

Service Worker 生命周期一般要比网页还要长，可以用来监控网页的状态；

网页可以通过 navigator.serviceWorker.controller.postMessage API 向掌管自己的 SW发送消息。


# 错误上报

## 通过 Ajax 发送数据

因为 Ajax 请求本身也有可能会发生异常，而且有可能会引发跨域问题，一般情况下更推荐使用动态创建 img 标签的形式进行上报。

## 动态创建 img 标签的形式
```
function report(error) {
  let reportUrl = 'http://jartto.wang/report';
  new Image().src = `${reportUrl}?logs=${error}`;
}
```
收集异常信息量太多，怎么办？实际中，我们不得不考虑这样一种情况：如果你的网站访问量很大，那么一个必然的错误发送的信息就有很多条，这时候，我们需要设置采集率，从而减缓服务器的压力：
```
Reporter.send = function(data) {
  // 只采集 30%
  if(Math.random() < 0.3) {
    send(data)      // 上报错误信息
  }
}
```
采集率应该通过实际情况来设定，随机数，或者某些用户特征都是不错的选择。
